//! Hexahedral mesh generation via sweep/extrusion.
//!
//! Creates a 3D hex mesh by extruding a 2D quad mesh (defined by `base_nx`
//! and `base_ny`) along the z-axis.  Supports variable layer heights for
//! boundary layer resolution near walls.

use gfd_core::mesh::cell::Cell;
use gfd_core::mesh::face::Face;
use gfd_core::mesh::node::Node;
use gfd_core::mesh::unstructured::{BoundaryPatch, UnstructuredMesh};

use crate::{MeshError, Result};

/// Builder for a hexahedral mesh generated by extruding a 2D quad mesh along z.
///
/// The base face is a uniform `base_nx x base_ny` quad mesh on the XY-plane
/// over `[0, lx] x [0, ly]`.  This base is then extruded through `num_layers`
/// layers along z, with heights specified by `layer_heights`.
///
/// # Example
/// ```
/// use gfd_mesh::unstructured::hexahedral::HexMesher;
///
/// let mesh = HexMesher::new(3, 3, 1.0, 1.0)
///     .with_uniform_layers(4, 0.5)
///     .build()
///     .unwrap();
/// assert_eq!(mesh.num_cells(), 3 * 3 * 4);
/// ```
pub struct HexMesher {
    /// Number of cells in x on the base face.
    base_nx: usize,
    /// Number of cells in y on the base face.
    base_ny: usize,
    /// Length in x.
    lx: f64,
    /// Length in y.
    ly: f64,
    /// Number of extrusion layers along z.
    num_layers: usize,
    /// Height of each extrusion layer. Length must equal `num_layers`.
    layer_heights: Vec<f64>,
}

impl HexMesher {
    /// Create a new hex mesher with the given base quad dimensions.
    ///
    /// You must call one of `with_uniform_layers` or `with_variable_layers`
    /// before building.
    pub fn new(base_nx: usize, base_ny: usize, lx: f64, ly: f64) -> Self {
        Self {
            base_nx,
            base_ny,
            lx,
            ly,
            num_layers: 0,
            layer_heights: Vec::new(),
        }
    }

    /// Set uniform extrusion layers.
    pub fn with_uniform_layers(mut self, num_layers: usize, total_height: f64) -> Self {
        self.num_layers = num_layers;
        let h = total_height / num_layers as f64;
        self.layer_heights = vec![h; num_layers];
        self
    }

    /// Set variable extrusion layer heights (e.g., for boundary layer grading).
    ///
    /// The number of layers is inferred from the length of `heights`.
    pub fn with_variable_layers(mut self, heights: Vec<f64>) -> Self {
        self.num_layers = heights.len();
        self.layer_heights = heights;
        self
    }

    /// Build the hex mesh.
    pub fn build(&self) -> Result<UnstructuredMesh> {
        if self.base_nx == 0 || self.base_ny == 0 {
            return Err(MeshError::InvalidParameters(
                "base_nx and base_ny must be > 0".to_string(),
            ));
        }
        if self.lx <= 0.0 || self.ly <= 0.0 {
            return Err(MeshError::InvalidParameters(
                "lx and ly must be > 0".to_string(),
            ));
        }
        if self.num_layers == 0 {
            return Err(MeshError::InvalidParameters(
                "Must have at least 1 layer (call with_uniform_layers or with_variable_layers)".to_string(),
            ));
        }
        if self.layer_heights.len() != self.num_layers {
            return Err(MeshError::InvalidParameters(
                "layer_heights length must equal num_layers".to_string(),
            ));
        }
        for (i, h) in self.layer_heights.iter().enumerate() {
            if *h <= 0.0 {
                return Err(MeshError::InvalidParameters(format!(
                    "layer_heights[{}] must be > 0, got {}",
                    i, h,
                )));
            }
        }

        let nx = self.base_nx;
        let ny = self.base_ny;
        let nl = self.num_layers;

        let dx = self.lx / nx as f64;
        let dy = self.ly / ny as f64;

        // Cumulative z-positions: z[0]=0, z[1]=h0, z[2]=h0+h1, ...
        let mut z_pos = Vec::with_capacity(nl + 1);
        z_pos.push(0.0);
        let mut cum = 0.0;
        for h in &self.layer_heights {
            cum += h;
            z_pos.push(cum);
        }

        // Node indexing: (i, j, k) where i in 0..=nx, j in 0..=ny, k in 0..=nl
        let node_idx = |i: usize, j: usize, k: usize| -> usize {
            k * (ny + 1) * (nx + 1) + j * (nx + 1) + i
        };

        // 1. Build nodes
        let num_nodes = (nx + 1) * (ny + 1) * (nl + 1);
        let mut nodes = Vec::with_capacity(num_nodes);
        for k in 0..=nl {
            for j in 0..=ny {
                for i in 0..=nx {
                    let id = node_idx(i, j, k);
                    nodes.push(Node::new(id, [i as f64 * dx, j as f64 * dy, z_pos[k]]));
                }
            }
        }

        // Cell indexing: (i, j, k) -> flat
        let cell_flat = |i: usize, j: usize, k: usize| -> usize {
            k * nx * ny + j * nx + i
        };

        // 2. Build cells
        let num_cells = nx * ny * nl;
        let mut cells = Vec::with_capacity(num_cells);
        for k in 0..nl {
            let layer_h = self.layer_heights[k];
            for j in 0..ny {
                for i in 0..nx {
                    let cell_id = cell_flat(i, j, k);

                    let n0 = node_idx(i, j, k);
                    let n1 = node_idx(i + 1, j, k);
                    let n2 = node_idx(i + 1, j + 1, k);
                    let n3 = node_idx(i, j + 1, k);
                    let n4 = node_idx(i, j, k + 1);
                    let n5 = node_idx(i + 1, j, k + 1);
                    let n6 = node_idx(i + 1, j + 1, k + 1);
                    let n7 = node_idx(i, j + 1, k + 1);

                    let cx = (i as f64 + 0.5) * dx;
                    let cy = (j as f64 + 0.5) * dy;
                    let cz = (z_pos[k] + z_pos[k + 1]) / 2.0;
                    let vol = dx * dy * layer_h;

                    cells.push(Cell::new(
                        cell_id,
                        vec![n0, n1, n2, n3, n4, n5, n6, n7],
                        Vec::new(),
                        vol,
                        [cx, cy, cz],
                    ));
                }
            }
        }

        // 3. Build faces
        let mut faces: Vec<Face> = Vec::new();
        let mut xmin_faces = Vec::new();
        let mut xmax_faces = Vec::new();
        let mut ymin_faces = Vec::new();
        let mut ymax_faces = Vec::new();
        let mut zmin_faces = Vec::new();
        let mut zmax_faces = Vec::new();

        // X-direction faces
        for k in 0..nl {
            let layer_h = self.layer_heights[k];
            for j in 0..ny {
                for i in 0..=nx {
                    let face_id = faces.len();
                    let fn0 = node_idx(i, j, k);
                    let fn1 = node_idx(i, j + 1, k);
                    let fn2 = node_idx(i, j + 1, k + 1);
                    let fn3 = node_idx(i, j, k + 1);
                    let face_nodes = vec![fn0, fn1, fn2, fn3];

                    let area = dy * layer_h;
                    let center = [
                        i as f64 * dx,
                        (j as f64 + 0.5) * dy,
                        (z_pos[k] + z_pos[k + 1]) / 2.0,
                    ];

                    let (owner, neighbor, normal);
                    if i == 0 {
                        owner = cell_flat(0, j, k);
                        neighbor = None;
                        normal = [-1.0, 0.0, 0.0];
                        xmin_faces.push(face_id);
                    } else if i == nx {
                        owner = cell_flat(nx - 1, j, k);
                        neighbor = None;
                        normal = [1.0, 0.0, 0.0];
                        xmax_faces.push(face_id);
                    } else {
                        owner = cell_flat(i - 1, j, k);
                        neighbor = Some(cell_flat(i, j, k));
                        normal = [1.0, 0.0, 0.0];
                    }

                    faces.push(Face::new(
                        face_id, face_nodes, owner, neighbor, area, normal, center,
                    ));
                }
            }
        }

        // Y-direction faces
        for k in 0..nl {
            let layer_h = self.layer_heights[k];
            for j in 0..=ny {
                for i in 0..nx {
                    let face_id = faces.len();
                    let fn0 = node_idx(i, j, k);
                    let fn1 = node_idx(i + 1, j, k);
                    let fn2 = node_idx(i + 1, j, k + 1);
                    let fn3 = node_idx(i, j, k + 1);
                    let face_nodes = vec![fn0, fn1, fn2, fn3];

                    let area = dx * layer_h;
                    let center = [
                        (i as f64 + 0.5) * dx,
                        j as f64 * dy,
                        (z_pos[k] + z_pos[k + 1]) / 2.0,
                    ];

                    let (owner, neighbor, normal);
                    if j == 0 {
                        owner = cell_flat(i, 0, k);
                        neighbor = None;
                        normal = [0.0, -1.0, 0.0];
                        ymin_faces.push(face_id);
                    } else if j == ny {
                        owner = cell_flat(i, ny - 1, k);
                        neighbor = None;
                        normal = [0.0, 1.0, 0.0];
                        ymax_faces.push(face_id);
                    } else {
                        owner = cell_flat(i, j - 1, k);
                        neighbor = Some(cell_flat(i, j, k));
                        normal = [0.0, 1.0, 0.0];
                    }

                    faces.push(Face::new(
                        face_id, face_nodes, owner, neighbor, area, normal, center,
                    ));
                }
            }
        }

        // Z-direction faces
        for k in 0..=nl {
            for j in 0..ny {
                for i in 0..nx {
                    let face_id = faces.len();
                    let fn0 = node_idx(i, j, k);
                    let fn1 = node_idx(i + 1, j, k);
                    let fn2 = node_idx(i + 1, j + 1, k);
                    let fn3 = node_idx(i, j + 1, k);
                    let face_nodes = vec![fn0, fn1, fn2, fn3];

                    let area = dx * dy;
                    let center = [
                        (i as f64 + 0.5) * dx,
                        (j as f64 + 0.5) * dy,
                        z_pos[k],
                    ];

                    let (owner, neighbor, normal);
                    if k == 0 {
                        owner = cell_flat(i, j, 0);
                        neighbor = None;
                        normal = [0.0, 0.0, -1.0];
                        zmin_faces.push(face_id);
                    } else if k == nl {
                        owner = cell_flat(i, j, nl - 1);
                        neighbor = None;
                        normal = [0.0, 0.0, 1.0];
                        zmax_faces.push(face_id);
                    } else {
                        owner = cell_flat(i, j, k - 1);
                        neighbor = Some(cell_flat(i, j, k));
                        normal = [0.0, 0.0, 1.0];
                    }

                    faces.push(Face::new(
                        face_id, face_nodes, owner, neighbor, area, normal, center,
                    ));
                }
            }
        }

        // 4. Boundary patches
        let mut boundary_patches = Vec::new();
        if !xmin_faces.is_empty() {
            boundary_patches.push(BoundaryPatch::new("xmin", xmin_faces));
        }
        if !xmax_faces.is_empty() {
            boundary_patches.push(BoundaryPatch::new("xmax", xmax_faces));
        }
        if !ymin_faces.is_empty() {
            boundary_patches.push(BoundaryPatch::new("ymin", ymin_faces));
        }
        if !ymax_faces.is_empty() {
            boundary_patches.push(BoundaryPatch::new("ymax", ymax_faces));
        }
        if !zmin_faces.is_empty() {
            boundary_patches.push(BoundaryPatch::new("zmin", zmin_faces));
        }
        if !zmax_faces.is_empty() {
            boundary_patches.push(BoundaryPatch::new("zmax", zmax_faces));
        }

        // 5. Populate cell face lists
        for face in &faces {
            cells[face.owner_cell].faces.push(face.id);
            if let Some(nbr) = face.neighbor_cell {
                cells[nbr].faces.push(face.id);
            }
        }

        Ok(UnstructuredMesh::from_components(
            nodes,
            faces,
            cells,
            boundary_patches,
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_basic_hex_mesh() {
        let mesh = HexMesher::new(3, 4, 3.0, 4.0)
            .with_uniform_layers(2, 2.0)
            .build()
            .unwrap();
        assert_eq!(mesh.num_cells(), 3 * 4 * 2);
        assert_eq!(mesh.num_nodes(), 4 * 5 * 3);
    }

    #[test]
    fn test_total_volume() {
        let lx = 2.0;
        let ly = 3.0;
        let total_h = 1.5;
        let mesh = HexMesher::new(5, 8, lx, ly)
            .with_uniform_layers(4, total_h)
            .build()
            .unwrap();
        let total_vol: f64 = mesh.cells.iter().map(|c| c.volume).sum();
        let expected = lx * ly * total_h;
        assert!(
            (total_vol - expected).abs() < 1e-10,
            "total vol {} expected {}",
            total_vol,
            expected,
        );
    }

    #[test]
    fn test_variable_layer_heights() {
        let heights = vec![0.01, 0.02, 0.04, 0.08, 0.16, 0.69];
        let total_h: f64 = heights.iter().sum();
        let mesh = HexMesher::new(2, 2, 1.0, 1.0)
            .with_variable_layers(heights)
            .build()
            .unwrap();
        assert_eq!(mesh.num_cells(), 2 * 2 * 6);

        let total_vol: f64 = mesh.cells.iter().map(|c| c.volume).sum();
        let expected = 1.0 * 1.0 * total_h;
        assert!(
            (total_vol - expected).abs() < 1e-10,
            "total vol {} expected {}",
            total_vol,
            expected,
        );

        // Check that bottom layer cells are smaller than top layer cells
        let bottom_cell = &mesh.cells[0]; // i=0, j=0, k=0
        let top_cell = &mesh.cells[2 * 2 * 5]; // i=0, j=0, k=5
        assert!(
            bottom_cell.volume < top_cell.volume,
            "bottom vol {} should be < top vol {}",
            bottom_cell.volume,
            top_cell.volume,
        );
    }

    #[test]
    fn test_boundary_patch_counts() {
        let nx = 4;
        let ny = 3;
        let nl = 2;
        let mesh = HexMesher::new(nx, ny, 1.0, 1.0)
            .with_uniform_layers(nl, 1.0)
            .build()
            .unwrap();

        let xmin = mesh.boundary_patch("xmin").unwrap();
        let xmax = mesh.boundary_patch("xmax").unwrap();
        let ymin = mesh.boundary_patch("ymin").unwrap();
        let ymax = mesh.boundary_patch("ymax").unwrap();
        let zmin = mesh.boundary_patch("zmin").unwrap();
        let zmax = mesh.boundary_patch("zmax").unwrap();

        assert_eq!(xmin.num_faces(), ny * nl);
        assert_eq!(xmax.num_faces(), ny * nl);
        assert_eq!(ymin.num_faces(), nx * nl);
        assert_eq!(ymax.num_faces(), nx * nl);
        assert_eq!(zmin.num_faces(), nx * ny);
        assert_eq!(zmax.num_faces(), nx * ny);
    }

    #[test]
    fn test_all_faces_positive_area() {
        let mesh = HexMesher::new(3, 3, 1.0, 1.0)
            .with_uniform_layers(3, 1.0)
            .build()
            .unwrap();
        for face in &mesh.faces {
            assert!(face.area > 0.0, "face {} has non-positive area", face.id);
        }
    }

    #[test]
    fn test_cell_faces_populated() {
        let mesh = HexMesher::new(2, 2, 1.0, 1.0)
            .with_uniform_layers(2, 1.0)
            .build()
            .unwrap();
        for cell in &mesh.cells {
            assert_eq!(
                cell.faces.len(),
                6,
                "cell {} has {} faces, expected 6",
                cell.id,
                cell.faces.len(),
            );
        }
    }

    #[test]
    fn test_invalid_parameters() {
        assert!(HexMesher::new(0, 3, 1.0, 1.0)
            .with_uniform_layers(1, 1.0)
            .build()
            .is_err());
        assert!(HexMesher::new(3, 3, -1.0, 1.0)
            .with_uniform_layers(1, 1.0)
            .build()
            .is_err());
        assert!(HexMesher::new(3, 3, 1.0, 1.0)
            .build()
            .is_err()); // no layers
    }

    #[test]
    fn test_single_layer() {
        let mesh = HexMesher::new(2, 2, 1.0, 1.0)
            .with_uniform_layers(1, 0.5)
            .build()
            .unwrap();
        assert_eq!(mesh.num_cells(), 4);
        let total_vol: f64 = mesh.cells.iter().map(|c| c.volume).sum();
        assert!((total_vol - 0.5).abs() < 1e-12);
    }
}
